const films = [
  {
    title: "Citizen Kane",
    director: "Orson Welles",
    year: 1941,
    genre: "drama",
    img: `https://media-cache.cinematerial.com/p/500x/xsgouqop/citizen-kane-movie-poster.jpg?v=1456238742`,
    description: `Citizen Kane is a 1941 American drama film produced by, directed by, and starring Orson Welles. He also co-wrote the screenplay with Herman J. Mankiewicz. The picture was Welles' first feature film. Citizen Kane is frequently cited as the greatest film ever made. For 50 consecutive years, it stood at number 1 in the British Film Institute's Sight & Sound decennial poll of critics, and it topped the American Film Institute's 100 Years ... 100 Movies list in 1998, as well as its 2007 update. The film was nominated for Academy Awards in nine categories and it won for Best Writing (Original Screenplay) by Mankiewicz and Welles. Citizen Kane is praised for Gregg Toland's cinematography, Robert Wise's editing, Bernard Herrmann's music, and its narrative structure, all of which have been considered innovative and precedent-setting.`,
    price: 1.99,
  },
  {
    title: "The Godfather",
    director: "Francis Ford Coppola",
    year: 1972,
    genre: "crime",
    img: `https://media-cache.cinematerial.com/p/500x/id2w2swk/the-godfather-movie-poster.jpg?v=1518295861`,
    description: `The Godfather is a 1972 American crime film directed by Francis Ford Coppola, who co-wrote the screenplay with Mario Puzo, based on Puzo's best-selling 1969 novel of the same name. The film stars Marlon Brando, Al Pacino, James Caan, Richard Castellano, Robert Duvall, Sterling Hayden, John Marley, Richard Conte, and Diane Keaton. It is the first installment in The Godfather trilogy, chronicling the Corleone family under patriarch Vito Corleone (Brando) from 1945 to 1955. It focuses on the transformation of his youngest son, Michael Corleone (Pacino), from reluctant family outsider to ruthless mafia boss.`,
    price: 1.99,
  },
  {
    title: "Casablanca",
    director: "Michael Curtiz",
    year: 1942,
    genre: ["drama", "romance"],
    img: `https://media-cache.cinematerial.com/p/500x/clstgyjv/casablanca-movie-poster.jpg?v=1456313334`,
    description: `Casablanca is a 1942 American romantic drama film directed by Michael Curtiz, and starring Humphrey Bogart, Ingrid Bergman, and Paul Henreid. Filmed and set during World War II, it focuses on an American expatriate (Bogart) who must choose between his love for a woman (Bergman) or helping her husband (Henreid), a Czech resistance leader, escape from the Vichy-controlled city of Casablanca to continue his fight against the Germans. The screenplay is based on Everybody Comes to Rick's, an unproduced stage play by Murray Burnett and Joan Alison. The supporting cast features Claude Rains, Conrad Veidt, Sydney Greenstreet, Peter Lorre, and Dooley Wilson.`,
    price: 1.99,
  },
  {
    title: "Raging Bull",
    director: "Martin Scorsese",
    year: 1980,
    genre: "drama",
    img: `https://media-cache.cinematerial.com/p/500x/thmrccxc/raging-bull-movie-poster.jpg?v=1456844941`,
    description: `Raging Bull is a 1980 American biographical sports drama film directed by Martin Scorsese, produced by Robert Chartoff and Irwin Winkler and adapted by Paul Schrader and Mardik Martin from Jake LaMotta's 1970 memoir Raging Bull: My Story. The film, distributed by United Artists, stars Robert De Niro as Jake LaMotta, an Italian-American middleweight boxer whose self-destructive and obsessive rage, jealousy and animalistic appetite destroyed his relationship with his wife and family. Also featured in the film are Joe Pesci as Joey, LaMotta's brother, and Cathy Moriarty as Vikki, his wife. Nicholas Colasanto, Theresa Saldana and Frank Vincent play supporting roles in the film.`,
    price: 1.99,
  },
  {
    title: "Singin' in the Rain",
    director: ["Gene Kelly", "Stanley Donen"],
    year: 1952,
    genre: ["musical", "comedy"],
    img: `https://media-cache.cinematerial.com/p/500x/2s3ekm3a/singin-in-the-rain-movie-poster.jpg?v=1456279743`,
    description: `Singin' in the Rain is a 1952 American musical romantic comedy film directed and choreographed by Gene Kelly and Stanley Donen, starring Kelly, Donald O'Connor, and Debbie Reynolds and featuring Jean Hagen, Millard Mitchell and Cyd Charisse. It offers a lighthearted depiction of Hollywood in the late 1920s, with the three stars portraying performers caught up in the transition from silent films to "talkies".`,
    price: 1.99,
  },
  {
    title: "Gone with the Wind",
    director: "Victor Fleming",
    year: 1939,
    genre: ["epic", "romance"],
    img: `https://media-cache.cinematerial.com/p/500x/lvggcvn5/gone-with-the-wind-movie-poster.jpg?v=1456242107`,
    description: `Gone with the Wind is a 1939 American epic historical romance film adapted from the 1936 novel by Margaret Mitchell. The film was produced by David O. Selznick of Selznick International Pictures and directed by Victor Fleming. Set in the American South against the backdrop of the American Civil War and the Reconstruction era, the film tells the story of Scarlett O'Hara (Vivien Leigh), the strong-willed daughter of a Georgia plantation owner, following her romantic pursuit of Ashley Wilkes (Leslie Howard), who is married to his cousin, Melanie Hamilton (Olivia de Havilland), and her subsequent marriage to Rhett Butler (Clark Gable).`,
    price: 1.49,
  },
  {
    title: "Lawrence of Arabia",
    director: "David Lean",
    year: 1962,
    genre: "epic",
    img: `https://media-cache.cinematerial.com/p/500x/n421gu7v/lawrence-of-arabia-movie-poster.jpg?v=1456600457`,
    description: `Lawrence of Arabia is a 1962 British epic historical drama film based on the life of T. E. Lawrence and his 1926 book Seven Pillars of Wisdom. It was directed by David Lean and produced by Sam Spiegel, through his British company Horizon Pictures and distributed by Columbia Pictures. The film stars Peter O'Toole as Lawrence with Alec Guinness playing Prince Faisal. The film also stars Jack Hawkins, Anthony Quinn, Omar Sharif, Anthony Quayle, Claude Rains and Arthur Kennedy. The screenplay was written by Robert Bolt and Michael Wilson.`,
    price: 1.99,
  },
  {
    title: "Schindler's List",
    director: "Steven Spielberg",
    year: 1993,
    genre: ["drama", "war"],
    img: `https://upload.wikimedia.org/wikipedia/en/3/38/Schindler%27s_List_movie.jpg`,
    description: `Schindler's List is a 1993 American epic historical drama film directed and produced by Steven Spielberg and written by Steven Zaillian. It is based on the 1982 novel Schindler's Ark by Australian novelist Thomas Keneally. The film follows Oskar Schindler, a German industrialist who saved more than a thousand mostly Polish-Jewish refugees from the Holocaust by employing them in his factories during World War II. It stars Liam Neeson as Schindler, Ralph Fiennes as SS officer Amon Göth, and Ben Kingsley as Schindler's Jewish accountant Itzhak Stern.`,
    price: 1.79,
  },
  {
    title: "Vertigo",
    director: "Alfred Hitchcock",
    year: 1958,
    genre: "mystery",
    img: `https://media-cache.cinematerial.com/p/500x/loyrwq2p/vertigo-movie-poster.jpg?v=1517778692`,
    description: `Vertigo is a 1958 American film noir psychological thriller film directed and produced by Alfred Hitchcock. The story was based on the 1954 novel D'entre les morts (From Among the Dead) by Boileau-Narcejac. The screenplay was written by Alec Coppel and Samuel A. Taylor. The film stars James Stewart as former police detective John "Scottie" Ferguson, who has retired because an incident in the line of duty has caused him to develop acrophobia (an extreme fear of heights) and vertigo (a false sense of rotational movement). Scottie is hired by an acquaintance, Gavin Elster, as a private investigator to follow Gavin's wife Madeleine (Kim Novak), who is behaving strangely.`,
    price: 1.99,
  },
  {
    title: "The Wizard of Oz",
    director: "Victor Fleming",
    year: 1939,
    genre: ["fantasy", "musical"],
    img: `https://media-cache.cinematerial.com/p/500x/9bfs4kbw/the-wizard-of-oz-re-release-movie-poster.jpg?v=1456505322`,
    description: `The Wizard of Oz is a 1939 American musical fantasy film produced by Metro-Goldwyn-Mayer (MGM). An adaptation of L. Frank Baum's 1900 children's fantasy novel The Wonderful Wizard of Oz, the film was primarily directed by Victor Fleming (who left the production to take over the troubled Gone with the Wind), and stars Judy Garland, Frank Morgan, Ray Bolger, Bert Lahr, Jack Haley, Billie Burke and Margaret Hamilton. Noel Langley, Florence Ryerson, and Edgar Allan Woolf received credit for the screenplay, but others made uncredited contributions. The music was composed by Harold Arlen and adapted by Herbert Stothart, with the lyrics written by Edgar "Yip" Harburg.`,
    price: 1.99,
  },
  {
    title: "City Lights",
    director: "Charlie Chaplin",
    year: 1931,
    genre: ["comedy", "drama", "romance"],
    img: `https://media-cache.cinematerial.com/p/500x/vc0xd8nu/city-lights-theatrical-movie-poster.jpg?v=1585300011`,
    description: `City Lights is a 1931 American silent romantic comedy film written, produced, directed by, and starring Charlie Chaplin. The story follows the misadventures of Chaplin's Tramp as he falls in love with a blind girl (Virginia Cherrill) and develops a turbulent friendship with an alcoholic millionaire (Harry Myers).`,
    price: 1.49,
  },
  {
    title: "The Searchers",
    director: "John Ford",
    year: 1956,
    genre: "western",
    img: `https://media-cache.cinematerial.com/p/500x/urcdoxeq/the-searchers-movie-poster.jpg?v=1456281123`,
    description: `The Searchers is a 1956 American Technicolor VistaVision epic Western film directed by John Ford and written by Frank S. Nugent, based on the 1954 novel by Alan Le May. It is set during the Texas-Native American wars, and stars John Wayne as a middle-aged Civil War veteran who spends years looking for his abducted niece (Natalie Wood), accompanied by his adopted nephew Martin (Jeffrey Hunter).`,
    price: 1.99,
  },
  {
    title: "Star Wars",
    director: "George Lucas",
    year: 1977,
    genre: "science fiction",
    img: `https://upload.wikimedia.org/wikipedia/en/8/87/StarWarsMoviePoster1977.jpg`,
    description: `Star Wars (retroactively titled Star Wars: Episode IV - A New Hope) is a 1977 American epic space opera film written and directed by George Lucas, produced by Lucasfilm and distributed by 20th Century Fox. It is the first film in the Star Wars film series and fourth chronological chapter of the "Skywalker Saga". Set "a long time ago" in a fictional universe where the galaxy is ruled by the tyrannical Galactic Empire, the story focuses on a group of freedom fighters known as the Rebel Alliance, who aim to destroy the Empire's newest weapon, the Death Star. Luke Skywalker becomes caught in the conflict while learning the ways of a metaphysical power known as "the Force" from Jedi Master Obi-Wan Kenobi. The cast includes Mark Hamill, Harrison Ford, Carrie Fisher, Peter Cushing, Alec Guinness, David Prowse, James Earl Jones, Anthony Daniels, Kenny Baker, and Peter Mayhew.`,
    price: 1.99,
  },
  {
    title: "Psycho",
    director: "Alfred Hitchcock",
    year: 1960,
    genre: "thriller",
    img: `https://media-cache.cinematerial.com/p/500x/0gxhwkwp/psycho-movie-poster.jpg?v=1456250506`,
    description: `Psycho is a 1960 American psychological horror thriller film produced and directed by Alfred Hitchcock. The screenplay, written by Joseph Stefano, was based on the 1959 novel of the same name by Robert Bloch. The film stars Anthony Perkins, Janet Leigh, Vera Miles, John Gavin and Martin Balsam. The plot centers on an encounter between on-the-run embezzler Marion Crane (Leigh) and shy motel proprietor Norman Bates (Perkins) and its aftermath, in which a private investigator (Balsam), Marion's lover Sam Loomis (Gavin), and her sister Lila (Miles) investigate her disappearance.`,
    price: 1.79,
  },
  {
    title: "2001: A Space Odyssey",
    director: "Stanley Kubrick",
    year: 1968,
    genre: "science fiction",
    img: `https://media-cache.cinematerial.com/p/500x/0gxhwkwp/psycho-movie-poster.jpg?v=1456250506`,
    description: `2001: A Space Odyssey is a 1968 epic science fiction film produced and directed by Stanley Kubrick. The screenplay was written by Kubrick and science fiction author Arthur C. Clarke, and was inspired by Clarke's 1951 short story "The Sentinel" and other short stories by Clarke. Clarke also published a novelisation of the film, in part written concurrently with the screenplay, after the film's release. The film stars Keir Dullea, Gary Lockwood, William Sylvester, and Douglas Rain, and follows a voyage by astronauts, scientists and the sentient supercomputer HAL to Jupiter to investigate an alien monolith.`,
    price: 1.99,
  },
  {
    title: "Sunset Boulevard",
    director: "Billy Wilder",
    year: 1950,
    genre: "drama",
    img: `https://media-cache.cinematerial.com/p/500x/hgy6d7jr/sunset-blvd-movie-poster.jpg?v=1456229033`,
    description: `Sunset Boulevard (styled in the main title on-screen as SUNSET BLVD.) is a 1950 American black comedy film noir directed and co-written by Billy Wilder, and produced and co-written by Charles Brackett. It was named after a major street that runs through Hollywood, the center of the American film industry.`,
    price: 1.89,
  },
  {
    title: "The Graduate",
    director: "Mike Nichols",
    year: 1967,
    genre: ["comedy", "drama"],
    img: `https://upload.wikimedia.org/wikipedia/en/8/8b/Graduateposter67.jpg`,
    description: `The Graduate is a 1967 American romantic comedy-drama film directed by Mike Nichols and written by Buck Henry and Calder Willingham, based on the 1963 novel of the same name by Charles Webb, who wrote it shortly after graduating from Williams College. The film tells the story of 21-year-old Benjamin Braddock (Dustin Hoffman), a recent college graduate with no well-defined aim in life, who is seduced by an older married woman, Mrs. Robinson (Anne Bancroft), but then falls for her daughter Elaine (Katharine Ross).`,
    price: 1.49,
  },
  {
    title: "The General",
    director: ["Buster Keaton", "Clyde Bruckman"],
    year: 1926,
    genre: "comedy",
    img: `https://media-cache.cinematerial.com/p/500x/1iakluzj/the-general-movie-poster.jpg?v=1456788038`,
    description: `The General is a 1926 American silent film released by United Artists. It was inspired by the Great Locomotive Chase, a true story of an event that occurred during the American Civil War. The story was adapted from the 1889 memoir The Great Locomotive Chase by William Pittenger. The film stars Buster Keaton who co-directed it with Clyde Bruckman.`,
    price: 1.99,
  },
  {
    title: "On the Waterfront",
    director: "Elia Kazan",
    year: 1954,
    genre: "drama",
    img: `https://media-cache.cinematerial.com/p/500x/exxtnuvk/on-the-waterfront-movie-poster.jpg?v=1602175362`,
    description: `On the Waterfront is a 1954 American crime drama film, directed by Elia Kazan and written by Budd Schulberg. It stars Marlon Brando and features Karl Malden, Lee J. Cobb, Rod Steiger, Pat Henning, and Eva Marie Saint in her film debut. The musical score was composed by Leonard Bernstein. The film was inspired by "Crime on the Waterfront" by Malcolm Johnson, a series of articles published in November-December 1948 in the New York Sun which won the 1949 Pulitzer Prize for Local Reporting, but the screenplay by Budd Schulberg is directly based on his own original story. The film focuses on union violence and corruption amongst longshoremen, while detailing widespread corruption, extortion, and racketeering on the waterfronts of Hoboken, New Jersey.`,
    price: 1.99,
  },
  {
    title: "It's a Wonderful Life",
    director: "Frank Capra",
    year: 1946,
    genre: ["comedy", "drama", "fanasy"],
    img: `https://media-cache.cinematerial.com/p/500x/inazrubw/its-a-wonderful-life-theatrical-movie-poster.jpg?v=1456721947`,
    description: `It's a Wonderful Life is a 1946 American Christmas fantasy drama film produced and directed by Frank Capra, based on the short story and booklet The Greatest Gift, which Philip Van Doren Stern self-published in 1943 and is in turn loosely based on the 1843 Charles Dickens novella A Christmas Carol. The film stars James Stewart as George Bailey, a man who has given up his personal dreams, in order to help others in his community, and whose thoughts of suicide on Christmas Eve brings about the intervention of his guardian angel, Clarence Odbody (Henry Travers).`,
    price: 1.99,
  },
  {
    title: "Chinatown",
    director: "Roman Polanski",
    year: 1974,
    genre: "mystery",
    img: `https://media-cache.cinematerial.com/p/500x/6llg8bbk/chinatown-movie-poster.jpg?v=1524006622`,
    description: `Chinatown is a 1974 American neo-noir mystery drama film directed by Roman Polanski from a screenplay by Robert Towne, starring Jack Nicholson and Faye Dunaway. The film was inspired by the California water wars, a series of disputes over southern California water at the beginning of the 20th century, by which Los Angeles interests secured water rights in the Owens Valley. The Robert Evans production, released by Paramount Pictures, was the director's last film in the United States and features many elements of film noir, particularly a multi-layered story that is part mystery and part psychological drama.`,
    price: 1.99,
  },
  {
    title: "Some Like It Hot",
    director: "Billy Wilder",
    year: 1959,
    genre: "comedy",
    img: `https://media-cache.cinematerial.com/p/500x/ixxvnfqe/some-like-it-hot-theatrical-movie-poster.jpg?v=1457396791`,
    description: `Some Like It Hot is a 1959 American crime comedy film directed, produced and co-written by Billy Wilder. It stars Marilyn Monroe, Tony Curtis and Jack Lemmon, with George Raft, Pat O'Brien, Joe E. Brown, Joan Shawlee, Grace Lee Whitney and Nehemiah Persoff in supporting roles. The screenplay by Wilder and I. A. L. Diamond is based on a screenplay by Robert Thoeren and Michael Logan from the 1935 French film Fanfare of Love. The film is about two musicians who disguise themselves by dressing as women to escape from mafia gangsters whom they witnessed committing a crime.`,
    price: 1.89,
  },
  {
    title: "The Grapes of Wrath",
    director: "John Ford",
    year: 1940,
    genre: "drama",
    img: `https://media-cache.cinematerial.com/p/500x/jlzcb43q/the-grapes-of-wrath-theatrical-movie-poster.jpg?v=1456258010`,
    description: `The Grapes of Wrath is a 1940 American drama film directed by John Ford. It was based on John Steinbeck's 1939 Pulitzer Prize-winning novel of the same name. The screenplay was written by Nunnally Johnson and the executive producer was Darryl F. Zanuck.`,
    price: 1.99,
  },
  {
    title: "E.T. the Extra-Terrestrial",
    director: "Steven Spielberg",
    year: 1982,
    genre: "science fiction",
    img: `https://upload.wikimedia.org/wikipedia/en/6/66/E_t_the_extra_terrestrial_ver3.jpg`,
    description: `E.T. the Extra-Terrestrial (or simply E.T.) is a 1982 American science fiction film produced and directed by Steven Spielberg and written by Melissa Mathison. It tells the story of Elliott, a boy who befriends an extraterrestrial, dubbed E.T., who is left behind on Earth. Along with his friends and family, Elliott must find a way to help E.T. find his way home. The film stars Dee Wallace, Henry Thomas, Peter Coyote, Robert MacNaughton and Drew Barrymore.`,
    price: 1.99,
  },
  {
    title: "To Kill a Mockingbird",
    director: "Robert Mulligan",
    year: 1962,
    genre: "drama",
    img: `https://media-cache.cinematerial.com/p/500x/ujcruib5/to-kill-a-mockingbird-movie-poster.jpg?v=1456172962`,
    description: `To Kill a Mockingbird is a 1962 American drama film directed by Robert Mulligan. The screenplay by Horton Foote is based on Harper Lee's 1960 Pulitzer Prize-winning novel of the same name. The film stars Gregory Peck as Atticus Finch and Mary Badham as Scout. It marked the film debut of Robert Duvall, William Windom and Alice Ghostley.`,
    price: 1.49,
  },
  {
    title: "Mr. Smith Goes to Washington",
    director: "Frank Capra",
    year: 1939,
    genre: ["comedy", "drama"],
    img: `https://media-cache.cinematerial.com/p/500x/fubztkgy/mr-smith-goes-to-washington-theatrical-movie-poster.jpg?v=1456011528`,
    description: `Mr. Smith Goes to Washington is a 1939 American political comedy-drama film directed by Frank Capra, starring Jean Arthur and James Stewart, and featuring Claude Rains and Edward Arnold. The film is about a newly appointed United States Senator who fights against a corrupt political system, and was written by Sidney Buchman, based on Lewis R. Foster's unpublished story "The Gentleman from Montana". The film was controversial when it was first released, but successful at the box office, and it made Stewart a major star. It was also loosely based on the life of Montana U.S. Senator Burton Wheeler, who underwent a similar experience when he was investigating the Warren Harding administration.`,
    price: 1.29,
  },
  {
    title: "High Noon",
    director: "Fred Zinnemann",
    year: 1952,
    genre: "western",
    img: `https://media-cache.cinematerial.com/p/500x/9vhrmdt6/high-noon-movie-poster.jpg?v=1456018274`,
    description: `High Noon is a 1952 American Western film produced by Stanley Kramer from a screenplay by Carl Foreman, directed by Fred Zinnemann, and starring Gary Cooper. The plot, which occurs in real time, centers on a town marshal whose sense of duty is tested when he must decide to either face a gang of killers alone, or leave town with his new wife.`,
    price: 0.99,
  },
  {
    title: "All About Eve",
    director: "Joseph L. Mankiewicz",
    year: 1950,
    genre: ["comedy", "drama"],
    img: `https://media-cache.cinematerial.com/p/500x/u2nxcjjc/all-about-eve-movie-poster.jpg?v=1456196904`,
    description: `All About Eve is a 1950 American drama film written and directed by Joseph L. Mankiewicz, and produced by Darryl F. Zanuck. It is based on the 1946 short story "The Wisdom of Eve" by Mary Orr, although Orr does not receive a screen credit.`,
    price: 1.49,
  },
  {
    title: "Double Indemnity",
    director: "Billy Wilder",
    year: 1944,
    genre: "crime",
    img: `https://media-cache.cinematerial.com/p/500x/hlfqodto/double-indemnity-theatrical-movie-poster.jpg?v=1456228189`,
    description: `Double Indemnity is a 1944 American crime film noir directed by Billy Wilder, co-written by Wilder and Raymond Chandler, and produced by Buddy DeSylva and Joseph Sistrom. The screenplay was based on James M. Cain's 1943 novel of the same title, which appeared as an eight-part serial for Liberty magazine in February 1936.`,
    price: 1.49,
  },
  {
    title: "Apocalypse Now",
    director: "Francis Ford Coppola",
    year: 1979,
    genre: "war",
    img: `https://media-cache.cinematerial.com/p/500x/ukmil45y/apocalypse-now-movie-poster.jpg?v=1667333108`,
    description: `Apocalypse Now is a 1979 American epic psychological war drama film directed, co-written and produced by Francis Ford Coppola and starring Marlon Brando, Robert Duvall, Martin Sheen, Frederic Forrest, Albert Hall, Sam Bottoms, Laurence Fishburne, and Dennis Hopper. The screenplay, co-written by Coppola and John Milius with narration written by Michael Herr, is loosely based on the 1899 novella Heart of Darkness by Joseph Conrad, with the setting changed from late 19th-century Congo to the Vietnam War. The film follows a river journey from South Vietnam into Cambodia undertaken by Captain Benjamin L. Willard (Martin Sheen), who is on a secret mission to assassinate Colonel Kurtz (Marlon Brando), a renegade Army Special Forces officer accused of murder and who is presumed insane.`,
    price: 1.99,
  },
  {
    title: "The Maltese Falcon",
    director: "John Huston",
    year: 1941,
    genre: "mystery",
    img: `https://media-cache.cinematerial.com/p/500x/dvim8oaw/the-maltese-falcon-movie-poster.jpg?v=1456231001`,
    description: `The Maltese Falcon is a 1941 American film noir written and directed by John Huston in his directorial debut, based on the 1930 novel of the same name by Dashiell Hammett and indebted to the 1931 movie of the same name. It stars Humphrey Bogart as private investigator Sam Spade and Mary Astor as his femme fatale client. Gladys George, Peter Lorre and Sydney Greenstreet co-star, with the last appearing in his film debut. The story follows a San Francisco private detective and his dealings with three unscrupulous adventurers, all of whom are competing to obtain a jewel-encrusted falcon statuette.`,
    price: 1.99,
  },
  {
    title: "The Godfather Part II",
    director: "Francis Ford Coppola",
    year: 1974,
    genre: "crime",
    img: `https://media-cache.cinematerial.com/p/500x/wzoo9uwk/the-godfather-part-ii-movie-poster.jpg?v=1518208982`,
    description: `The Godfather Part II is a 1974 American epic crime film produced and directed by Francis Ford Coppola. The film is partially based on the 1969 novel The Godfather by Mario Puzo, who co-wrote the screenplay with Coppola. Part II serves as both a sequel and a prequel to the 1972 film The Godfather, presenting parallel dramas: one picks up the 1958 story of Michael Corleone (Al Pacino), the new Don of the Corleone family, protecting the family business in the aftermath of an attempt on his life; the prequel covers the journey of his father, Vito Corleone (Robert De Niro), from his Sicilian childhood to the founding of his family enterprise in New York City. The ensemble cast also features Robert Duvall, Diane Keaton, Talia Shire, Morgana King, John Cazale, Mariana Hill, and Lee Strasberg.`,
    price: 1.59,
  },
  {
    title: "One Flew Over the Cuckoo's Nest",
    director: "Milos Forman",
    year: 1975,
    genre: ["comedy", "drama"],
    img: `https://media-cache.cinematerial.com/p/500x/vlv0lthy/one-flew-over-the-cuckoos-nest-movie-poster.jpg?v=1456249203`,
    description: `One Flew Over the Cuckoo's Nest is a 1975 American psychological comedy drama film directed by Miloš Forman, based on the 1962 novel of the same name by Ken Kesey. The film stars Jack Nicholson who plays a new patient at a mental institution alongside Louise Fletcher who plays an austere nurse. It also features a supporting cast of Will Sampson, Danny DeVito, Sydney Lassick, William Redfield, as well as Christopher Lloyd and Brad Dourif in their film debuts.`,
    price: 1.99,
  },
  {
    title: "Snow White and the Seven Dwarfs",
    director: "David Hand",
    year: 1937,
    genre: ["children's", "fantasy"],
    img: `https://upload.wikimedia.org/wikipedia/en/4/49/Snow_White_1937_poster.png`,
    description: `Snow White and the Seven Dwarfs is a 1937 American animated musical fantasy film produced by Walt Disney Productions and released by RKO Radio Pictures. Based on the 1812 German fairy tale by the Brothers Grimm, it is the first full-length traditionally animated feature film and the first Disney animated feature film. The story was adapted by storyboard artists Dorothy Ann Blank, Richard Creedon, Merrill De Maris, Otto Englander, Earl Hurd, Dick Rickard, Ted Sears and Webb Smith. David Hand was the supervising director, while William Cottrell, Wilfred Jackson, Larry Morey, Perce Pearce, and Ben Sharpsteen directed the film's individual sequences.`,
    price: 1.29,
  },
  {
    title: "Annie Hall",
    director: "Woody Allen",
    year: 1977,
    genre: "comedy",
    img: `https://upload.wikimedia.org/wikipedia/en/e/e6/Anniehallposter.jpg`,
    description: `Annie Hall is a 1977 American satirical romantic comedy-drama film directed by Woody Allen from a screenplay written by him and Marshall Brickman, and produced by Allen's manager, Charles H. Joffe. The film stars Allen as Alvy Singer, who tries to figure out the reasons for the failure of his relationship with the eponymous female lead, played by Diane Keaton in a role written specifically for her.`,
    price: 1.99,
  },
  {
    title: "The Bridge on the River Kwai",
    director: "David Lean",
    year: 1957,
    genre: ["war", "drama"],
    img: `https://upload.wikimedia.org/wikipedia/en/0/09/TheBridgeOverTheRiverKwai.jpg`,
    description: `The Bridge on the River Kwai is a 1957 epic war film directed by David Lean and based on the 1952 novel written by Pierre Boulle. Although the film uses the historical setting of the construction of the Burma Railway in 1942-1943, the plot and characters of Boulle's novel and the screenplay are almost entirely fictional. The cast includes William Holden, Alec Guinness, Jack Hawkins, and Sessue Hayakawa.`,
    price: 1.99,
  },
  {
    title: "The Best Years of Our Lives",
    director: "William Wyler",
    year: 1946,
    genre: ["drama", "epic"],
    img: `https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/The_Best_Years_of_Our_Lives_%281946_poster%29.jpg/800px-The_Best_Years_of_Our_Lives_%281946_poster%29.jpg`,
    description: `The Best Years of Our Lives (also known as Glory for Me and Home Again) is a 1946 American epic drama film directed by William Wyler, and starring Myrna Loy, Fredric March, Dana Andrews, Teresa Wright, Virginia Mayo and Harold Russell. The film is about three United States servicemen re-adjusting to societal changes and civilian life after coming home from World War II. The three men come from different services with different ranks that do not correspond with their civilian social class backgrounds.`,
    price: 1.99,
  },
  {
    title: "The Treasure of the Sierra Madre",
    director: "John Huston",
    year: 1948,
    genre: ["action", "adventure", "drama"],
    img: `https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/The_Treasure_of_the_Sierra_Madre_%281947_poster%29.jpg/800px-The_Treasure_of_the_Sierra_Madre_%281947_poster%29.jpg`,
    description: `The Treasure of the Sierra Madre is a 1948 American Western film written and directed by John Huston. It is an adaptation of B. Traven's 1927 novel of the same name, set in 1925, and follows two downtrodden men (played by Humphrey Bogart and Tim Holt) who join forces with a grizzled old prospector (Walter Huston, the director's father), in searching for gold in Mexico.`,
    price: 1.89,
  },
  {
    title:
      "Dr. Strangelove Or: How I Learned to Stop Worrying and Love the Bomb",
    director: "Stanley Kubrick",
    year: 1964,
    genre: "comedy",
    img: `https://media-cache.cinematerial.com/p/500x/eigilxso/dr-strangelove-movie-poster.jpg?v=1601744855`,
    description: `Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb, known simply and more commonly as Dr. Strangelove, is a 1964 black comedy film that satirizes the Cold War fears of a nuclear conflict between the Soviet Union and the United States. The film was directed, produced, and co-written by Stanley Kubrick and stars Peter Sellers, George C. Scott, Sterling Hayden, and Slim Pickens. The film was made in the United Kingdom. The film is loosely based on Peter George's thriller novel Red Alert (1958).`,
    price: 1.99,
  },
  {
    title: "The Sound of Music",
    director: "Robert Wise",
    year: 1965,
    genre: ["musical", "children's"],
    img: `https://media-cache.cinematerial.com/p/500x/kx2sid6q/the-sound-of-music-movie-poster.jpg?v=1456312615`,
    description: `The Sound of Music is a 1965 American musical drama film produced and directed by Robert Wise, and starring Julie Andrews and Christopher Plummer, with Richard Haydn, Peggy Wood, Charmian Carr, and Eleanor Parker. The film is an adaptation of the 1959 stage musical of the same name, composed by Richard Rodgers with lyrics by Oscar Hammerstein II. The film's screenplay was written by Ernest Lehman, adapted from the stage musical's book by Lindsay and Crouse. Based on the 1949 memoir The Story of the Trapp Family Singers by Maria von Trapp, the film is about a young Austrian postulant in Salzburg, Austria, in 1938 who is sent to the villa of a retired naval officer and widower to be governess to his seven children. After bringing love and music into the lives of the family, she marries the officer and, together with the children, finds a way to survive the loss of their homeland to the Nazis.`,
    price: 1.99,
  },
  {
    title: "King Kong",
    director: ["Merian C. Cooper", "Ernest B. Schoedsack"],
    year: 1933,
    genre: "adventure",
    img: `https://media-cache.cinematerial.com/p/500x/coccxh3a/king-kong-movie-poster.jpg?v=1456190791`,
    description: `King Kong is a fictional giant monster resembling an enormous gorilla, who has appeared in various media since 1933. He has been dubbed The Eighth Wonder of the World, a phrase commonly used within the franchise. His first appearance was in the novelization of the 1933 film King Kong from RKO Pictures, with the film premiering a little over two months later. Upon its initial release and subsequent re-releases, the film received universal acclaim. A sequel quickly followed that same year with The Son of Kong, featuring Little Kong. Toho produced King Kong vs. Godzilla (1962) featuring a giant Kong battling Toho's Godzilla and King Kong Escapes (1967), a film loosely based on Rankin/Bass' The King Kong Show (1966-1969). In 1976, Dino De Laurentiis produced a modern remake of the original film directed by John Guillermin. A sequel, King Kong Lives, followed a decade later featuring a Lady Kong. Another remake of the original, this time set in 1933, was released in 2005 by filmmaker Peter Jackson.`,
    price: 1.49,
  },
  {
    title: "Bonnie and Clyde",
    director: "Arthur Penn",
    year: 1967,
    genre: "crime",
    img: `https://media-cache.cinematerial.com/p/500x/u2f5ebz2/bonnie-and-clyde-movie-poster.jpg?v=1456275366`,
    description: `Bonnie and Clyde is a 1967 American biographical neo-noir crime drama film directed by Arthur Penn and starring Warren Beatty and Faye Dunaway as the title characters Clyde Barrow and Bonnie Parker. The film also features Michael J. Pollard, Gene Hackman, and Estelle Parsons. The screenplay is by David Newman and Robert Benton. Robert Towne and Beatty provided uncredited contributions to the script; Beatty produced the film. The music is by Charles Strouse.`,
    price: 1.99,
  },
  {
    title: "Midnight Cowboy",
    director: "John Schlesinger",
    year: 1969,
    genre: "drama",
    img: `https://media-cache.cinematerial.com/p/500x/sqdsxako/midnight-cowboy-movie-poster.jpg?v=1456284516`,
    description: `Midnight Cowboy is a 1969 American drama film, based on the 1965 novel of the same name by James Leo Herlihy. The film was written by Waldo Salt, directed by John Schlesinger, and stars Dustin Hoffman and Jon Voight, with notable smaller roles being filled by Sylvia Miles, John McGiver, Brenda Vaccaro, Bob Balaban, Jennifer Salt, and Barnard Hughes. Set in New York City, Midnight Cowboy depicts the unlikely friendship between two hustlers: naïve sex worker Joe Buck (Voight), and ailing con man Enrico "Ratso" Rizzo (Hoffman).`,
    price: 1.99,
  },
  {
    title: "The Philadelphia Story",
    director: "George Cukor",
    year: 1940,
    genre: ["comedy", "romance"],
    img: `https://media-cache.cinematerial.com/p/500x/jy51c4tf/the-philadelphia-story-movie-poster.jpg?v=1456289347`,
    description: `The Philadelphia Story is a 1940 American romantic comedy film directed by George Cukor, starring Cary Grant, Katharine Hepburn, James Stewart, and Ruth Hussey. Based on the 1939 Broadway play of the same name by Philip Barry, the film is about a socialite whose wedding plans are complicated by the simultaneous arrival of her ex-husband and a tabloid magazine journalist. The socialite character of the play—performed by Hepburn in the film—was inspired by Helen Hope Montgomery Scott (1904-1995), a Philadelphia socialite known for her hijinks, who married a friend of playwright Barry.`,
    price: 1.99,
  },
  {
    title: "Shane",
    director: "George Stevens",
    year: 1953,
    genre: "western",
    img: `https://media-cache.cinematerial.com/p/500x/nr0jzirs/shane-movie-poster.jpg?v=1456005314`,
    description: `Shane is a 1953 American Technicolor Western film starring Alan Ladd, Jean Arthur and Van Heflin. Released by Paramount Pictures, the film is noted for its landscape cinematography, editing, performances, and contributions to the genre. The picture was produced and directed by George Stevens from a screenplay by A. B. Guthrie Jr., based on the 1949 novel of the same name by Jack Schaefer. Its Oscar-winning cinematography was by Loyal Griggs.`,
    price: 1.79,
  },
  {
    title: "It Happened One Night",
    director: "Frank Capra",
    year: 1934,
    genre: "comedy",
    img: `https://media-cache.cinematerial.com/p/500x/tcrmgpm1/it-happened-one-night-theatrical-movie-poster.jpg?v=1456320410`,
    description: `It Happened One Night is a 1934 pre-Code American romantic comedy film with elements of screwball comedy directed and co-produced by Frank Capra, in collaboration with Harry Cohn, in which a pampered socialite (Claudette Colbert) tries to get out from under her father's thumb and falls in love with a roguish reporter (Clark Gable). The screenplay by Robert Riskin is based on the August 1933 short story "Night Bus" by Samuel Hopkins Adams, which provided the shooting title. Classified as a "pre-Code" production, the film is among the last romantic comedies created before the MPPDA began rigidly enforcing the 1930 Motion Picture Production Code in July 1934. It Happened One Night was released just four months prior to that enforcement.`,
    price: 1.99,
  },
  {
    title: "A Streetcar Named Desire",
    director: "Elia Kazan",
    year: 1951,
    genre: "drama",
    img: `https://media-cache.cinematerial.com/p/500x/n6wyu9mi/a-streetcar-named-desire-movie-poster.jpg?v=1456260455`,
    description: `A Streetcar Named Desire is a 1951 American Southern Gothic drama film, adapted from Tennessee Williams's Pulitzer Prize-winning play of the same name. It is directed by Elia Kazan, and stars Vivien Leigh, Marlon Brando, Kim Hunter, and Karl Malden. The film tells the story of a Mississippi Southern belle, Blanche DuBois, who, after encountering a series of personal losses, seeks refuge with her sister and brother-in-law in a dilapidated New Orleans apartment building. The original Broadway production and cast was converted to film, albeit with several changes and sanitizations related to censorship.`,
    price: 1.99,
  },
  {
    title: "Rear Window",
    director: "Alfred Hitchcock",
    year: 1954,
    genre: ["mystery", "thriller"],
    img: `https://media-cache.cinematerial.com/p/500x/bpdkww74/rear-window-theatrical-movie-poster.jpg?v=1456553037`,
    description: `Rear Window is a 1954 American mystery thriller film directed by Alfred Hitchcock and written by John Michael Hayes based on Cornell Woolrich's 1942 short story "It Had to Be Murder". Originally released by Paramount Pictures, the film stars James Stewart, Grace Kelly, Wendell Corey, Thelma Ritter, and Raymond Burr. It was screened at the 1954 Venice Film Festival.`,
    price: 1.99,
  },
  {
    title: "Intolerance",
    director: "D. W. Griffith",
    year: 1916,
    genre: "epic",
    img: `https://media-cache.cinematerial.com/p/500x/2seblhji/intolerance-loves-struggle-through-the-ages-movie-poster.jpg?v=1456805155`,
    description: `Regarded as one of the most influential films of the silent era (though it received mixed reviews at the time), the three-and-a-half-hour epic, Intolerance, intercuts four parallel storylines, each separated by several centuries: first, a contemporary melodrama of crime and redemption; second, a Judean story: Christ's mission and death; third, a French story: the events surrounding the St. Bartholomew's Day massacre of 1572; and fourth, a Babylonian story: the fall of the Babylonian Empire to Persia in 539 BC. Each story had its own distinctive color tint in the original print. The scenes are linked by shots of a figure representing Eternal Motherhood, rocking a cradle.`,
    price: 1.29,
  },
  {
    title: "The Lord of the Rings: The Fellowship of the Ring",
    director: "Peter Jackson",
    year: 2001,
    genre: ["fantasy", "epic"],
    img: `https://upload.wikimedia.org/wikipedia/en/8/8a/The_Lord_of_the_Rings_The_Fellowship_of_the_Ring_%282001%29.jpg`,
    description: `The Lord of the Rings: The Fellowship of the Ring is a 2001 epic fantasy adventure film directed by Peter Jackson from a screenplay by Fran Walsh, Philippa Boyens, and Jackson, based on 1954's The Fellowship of the Ring, the first volume of the novel The Lord of the Rings by J. R. R. Tolkien. The film is the first installment in The Lord of the Rings trilogy. It features an ensemble cast including Elijah Wood, Ian McKellen, Liv Tyler, Viggo Mortensen, Sean Astin, Cate Blanchett, John Rhys-Davies, Billy Boyd, Dominic Monaghan, Orlando Bloom, Christopher Lee, Hugo Weaving, Sean Bean, Ian Holm, and Andy Serkis.`,
    price: 1.99,
  },
  {
    title: "West Side Story",
    director: ["Jerome Robbins", "Robert Wise"],
    year: 1961,
    genre: ["crime", "drama", "musical"],
    img: `https://media-cache.cinematerial.com/p/500x/wqecdokr/west-side-story-movie-poster.jpg?v=1456543329`,
    description: `West Side Story is a 1961 American musical romantic drama film directed by Robert Wise and Jerome Robbins. With a screenplay by Ernest Lehman, the film is an adaptation of the 1957 Broadway musical of the same title, which in turn was inspired by Shakespeare's play Romeo and Juliet. It stars Natalie Wood, Richard Beymer, Russ Tamblyn, Rita Moreno, and George Chakiris, and was photographed by Daniel L. Fapp in Super Panavision 70. The music was composed by Leonard Bernstein, with lyrics by Stephen Sondheim.`,
    price: 1.99,
  },
  {
    title: "Taxi Driver",
    director: "Martin Scorsese",
    year: 1976,
    genre: "drama",
    img: `https://media-cache.cinematerial.com/p/500x/uqh3oawo/taxi-driver-movie-poster.jpg?v=1456645786`,
    description: `Taxi Driver is a 1976 American film directed by Martin Scorsese, written by Paul Schrader, and starring Robert De Niro, Jodie Foster, Cybill Shepherd, Harvey Keitel, Peter Boyle, Leonard Harris, and Albert Brooks. Set in a decaying and morally bankrupt New York City following the Vietnam War, the film follows Travis Bickle (De Niro), a veteran working as a taxi driver, and his deteriorating mental state as he works nights in the city.`,
    price: 1.99,
  },
  {
    title: "The Deer Hunter",
    director: "Michael Cimino",
    year: 1978,
    genre: "drama",
    img: `https://media-cache.cinematerial.com/p/500x/yepnv2yo/the-deer-hunter-british-movie-poster.jpg?v=1477955725`,
    description: `The Deer Hunter is a 1978 war drama film co-written and directed by Michael Cimino about a trio of Slavic-American steelworkers whose lives were upended after fighting in the Vietnam War. The three soldiers are played by Robert De Niro, Christopher Walken, and John Savage, with John Cazale (in his final role), Meryl Streep, and George Dzundza playing supporting roles. The story takes place in Clairton, Pennsylvania, a working-class town on the Monongahela River south of Pittsburgh, and in Vietnam.`,
    price: 1.99,
  },
  {
    title: "M*A*S*H",
    director: "Robert Altman",
    year: 1970,
    genre: ["comedy", "drama", "war"],
    img: `https://media-cache.cinematerial.com/p/500x/agpsghbe/mash-theatrical-movie-poster.jpg?v=1456582580`,
    description: `M*A*S*H (stylized on-screen as MASH) is a 1970 American black comedy war film directed by Robert Altman and written by Ring Lardner Jr., based on Richard Hooker's 1968 novel MASH: A Novel About Three Army Doctors. The picture is the only theatrically released feature film in the M*A*S*H franchise, and it became one of the biggest films of the early 1970s for 20th Century Fox.`,
    price: 1.99,
  },
  {
    title: "North by Northwest",
    director: "Alfred Hitchcock",
    year: 1959,
    genre: ["thriller", "spy"],
    img: `https://media-cache.cinematerial.com/p/500x/llwhnozg/north-by-northwest-movie-poster.jpg?v=1456277470`,
    description: `North by Northwest is a 1959 American spy thriller film, produced and directed by Alfred Hitchcock and starring Cary Grant, Eva Marie Saint and James Mason. The screenplay was by Ernest Lehman, who wanted to write "the Hitchcock picture to end all Hitchcock pictures".`,
    price: 1.79,
  },
  {
    title: "Jaws",
    director: "Steven Spielberg",
    year: 1975,
    genre: ["thriller", "adventure"],
    img: `https://upload.wikimedia.org/wikipedia/en/e/eb/JAWS_Movie_poster.jpg`,
    description: `Jaws is a 1975 American thriller film directed by Steven Spielberg, based on the 1974 novel by Peter Benchley. It stars Roy Scheider as police chief Martin Brody, who, with the help of a marine biologist (Richard Dreyfuss) and a professional shark hunter (Robert Shaw), hunts a man-eating great white shark that attacks beachgoers at a summer resort town. Murray Hamilton plays the mayor, and Lorraine Gary portrays Brody's wife. The screenplay is credited to Benchley, who wrote the first drafts, and actor-writer Carl Gottlieb, who rewrote the script during principal photography.`,
    price: 1.99,
  },
  {
    title: "Rocky",
    director: "John G. Avildsen",
    year: 1976,
    genre: "drama",
    img: `https://media-cache.cinematerial.com/p/500x/eznpndls/rocky-movie-poster.jpg?v=1456305781`,
    description: `Rocky is a 1976 American sports drama film directed by John G. Avildsen and written by and starring Sylvester Stallone. It is the first installment in the Rocky franchise. It also stars Talia Shire, Burt Young, Carl Weathers, and Burgess Meredith. In the film, Rocky Balboa (Stallone), an uneducated, small-time club fighter and debt collector gets an unlikely shot at the world heavyweight championship held by Apollo Creed (Weathers).`,
    price: 1.99,
  },
  {
    title: "The Gold Rush",
    director: "Charlie Chaplin",
    year: 1925,
    genre: "comedy",
    img: `https://media-cache.cinematerial.com/p/500x/ltpqy9hf/the-gold-rush-movie-poster.jpg?v=1456790793`,
    description: `The Gold Rush is a 1925 American silent comedy film written, produced, and directed by Charlie Chaplin. The film also stars Chaplin in his Little Tramp persona, Georgia Hale, Mack Swain, Tom Murray, Henry Bergman, and Malcolm Waite.`,
    price: 1.29,
  },
  {
    title: "Nashville",
    director: "Robert Altman",
    year: 1975,
    genre: "drama",
    img: "https://media-cache.cinematerial.com/p/500x/ilridq7r/nashville-swedish-movie-poster.jpg?v=1456226799",
    description: `Nashville is a 1975 American satirical musical ensemble comedy-drama film directed and produced by Robert Altman. The film follows various people involved in the country and gospel music businesses in Nashville, Tennessee, over a five-day period, leading up to a gala concert for a populist outsider running for President on the Replacement Party ticket.`,
    price: 1.79,
  },
  {
    title: "Duck Soup",
    director: "Leo McCarey",
    year: 1933,
    genre: "comedy",
    img: `https://media-cache.cinematerial.com/p/500x/6qacfjaf/duck-soup-movie-poster.jpg?v=1456222653`,
    description: `Duck Soup is a 1933 American pre-Code musical black comedy film written by Bert Kalmar and Harry Ruby, with additional dialogue by Arthur Sheekman and Nat Perrin, directed by Leo McCarey. Released theatrically by Paramount Pictures on November 17, 1933, it starred the Marx Brothers (Groucho, Harpo, Chico, and Zeppo in his final Marx Brothers' movie) and also featured Margaret Dumont, Louis Calhern, Raquel Torres and Edgar Kennedy. It was the last of five Marx Brothers movies released by Paramount Pictures. Groucho plays the newly installed president of the mythical country of Freedonia. Zeppo is his secretary, while Harpo and Chico are Sylvanian spies. Relations between Groucho and the Sylvanian ambassador deteriorate during the film, and they go to war at the conclusion.`,
    price: 1.79,
  },
  {
    title: "Sullivan's Travels",
    director: "Preston Sturges",
    year: 1941,
    genre: "comedy",
    img: `https://media-cache.cinematerial.com/p/500x/n0idrz86/sullivans-travels-movie-poster.jpg?v=1456491192`,
    description: `Sullivan's Travels is a 1941 American comedy film written and directed by Preston Sturges. A satire on the film industry, it follows a famous Hollywood comedy director (Joel McCrea) who, longing to make a socially relevant drama, sets out to live as a tramp to gain life experience for his forthcoming film. Along the way he unites with a poor aspiring actress (Veronica Lake) who accompanies him. The title is a reference to Gulliver's Travels, the 1726 novel by satirist Jonathan Swift about another journey of self-discovery.`,
    price: 1.99,
  },
  {
    title: "American Graffiti",
    director: "George Lucas",
    year: 1973,
    genre: ["comedy", "drama"],
    img: `https://upload.wikimedia.org/wikipedia/en/e/e6/American_graffiti_ver1.jpg`,
    description: `American Graffiti is a 1973 American coming-of-age comedy-drama film directed by George Lucas, produced by Francis Ford Coppola, written by Willard Huyck, Gloria Katz and Lucas, and starring Richard Dreyfuss, Ron Howard (billed as Ronny Howard), Paul Le Mat, Harrison Ford, Charles Martin Smith, Cindy Williams, Candy Clark, Mackenzie Phillips, Bo Hopkins, and Wolfman Jack. Suzanne Somers, Kathleen Quinlan, Debralee Scott, and Joe Spano also appear in the film.`,
    price: 1.99,
  },
  {
    title: "Cabaret",
    director: "Bob Fosse",
    year: 1972,
    genre: "musical",
    img: `https://media-cache.cinematerial.com/p/500x/d7bdt8lu/cabaret-movie-poster.jpg?v=1502145830`,
    description: `Cabaret is a 1972 American musical drama film directed by Bob Fosse, and starring Liza Minnelli, Michael York and Joel Grey. Set in Berlin during the Weimar Republic in 1931, under the presence of the growing Nazi Party, the film is loosely based on the 1966 Broadway musical Cabaret by Kander and Ebb, which was adapted from Christopher Isherwood's semi-autobiographical novel The Berlin Stories (1945) as well as John Van Druten's 1951 play I Am a Camera, which was itself adapted from Isherwood's novel. Multiple numbers from the stage score were used for the film, which also featured three other songs by Kander and Ebb, including two written for the adaptation.`,
    price: 1.99,
  },
  {
    title: "Network",
    director: "Sidney Lumet",
    year: 1976,
    genre: ["comedy", "drama"],
    img: `https://media-cache.cinematerial.com/p/500x/bdehtgrj/network-movie-poster.jpg?v=1456315692`,
    description: `Network is a 1976 American satirical black comedy-drama film released by Metro-Goldwyn-Mayer, written by Paddy Chayefsky and directed by Sidney Lumet. It is about a fictional television network, UBS, and its struggle with poor ratings. The film stars Faye Dunaway, William Holden, Peter Finch (in his final film role), Robert Duvall, Wesley Addy, Ned Beatty, and Beatrice Straight.`,
    price: 1.99,
  },
  {
    title: "The African Queen",
    director: "John Huston",
    year: 1951,
    genre: ["adventure", "romance"],
    img: `https://media-cache.cinematerial.com/p/500x/zsrvcpk4/the-african-queen-movie-poster.jpg?v=1456541616`,
    description: `The African Queen is a 1951 British-American adventure film adapted from the 1935 novel of the same name by C. S. Forester. The film was directed by John Huston and produced by Sam Spiegel and John Woolf. The screenplay was adapted by James Agee, John Huston, John Collier and Peter Viertel. It was photographed in Technicolor by Jack Cardiff and has a music score by Allan Gray. The film stars Humphrey Bogart (who won the Academy Award for Best Actor, his only Oscar) and Katharine Hepburn with Robert Morley, Peter Bull, Walter Gotell, Richard Marner and Theodore Bikel.`,
    price: 1.99,
  },
  {
    title: "Raiders of the Lost Ark",
    director: "Steven Spielberg",
    year: 1981,
    genre: ["action", "adventure"],
    img: `https://upload.wikimedia.org/wikipedia/en/a/a6/Raiders_of_the_Lost_Ark_Theatrical_Poster.jpg`,
    description: `Raiders of the Lost Ark is a 1981 American action-adventure film directed by Steven Spielberg and written by Lawrence Kasdan, based on a story by George Lucas and Philip Kaufman. It stars Harrison Ford, Karen Allen, Paul Freeman, Ronald Lacey, John Rhys-Davies, and Denholm Elliott. Ford portrays Indiana Jones, a globe-trotting archaeologist vying with Nazi German forces in 1936 to recover the long-lost Ark of the Covenant, a relic said to make an army invincible. Teaming up with his tough former lover Marion Ravenwood (Allen), Jones races to stop rival archaeologist Dr. René Belloq (Freeman) from guiding the Nazis to the Ark and its power.`,
    price: 1.99,
  },
  {
    title: "Who's Afraid of Virginia Woolf?",
    director: "Mike Nichols",
    year: 1966,
    genre: "drama",
    img: `https://media-cache.cinematerial.com/p/500x/fipiwvjd/whos-afraid-of-virginia-woolf-movie-poster.jpg?v=1456214894`,
    description: `Who's Afraid of Virginia Woolf? is a 1966 American drama film directed by Mike Nichols in his directorial debut. The screenplay by Ernest Lehman is an adaptation of Edward Albee's 1962 play of the same name. It stars Elizabeth Taylor as Martha, Richard Burton as George, George Segal as Nick, and Sandy Dennis as Honey. The film depicts a late-night gathering at the home of George, a college history professor, and his wife Martha, the daughter of the university's president. The guests are Nick, a new biology professor at the school, and his wife, Honey.`,
    price: 1.79,
  },
  {
    title: "Unforgiven",
    director: "Clint Eastwood",
    year: 1992,
    genre: ["western", "drama"],
    img: `https://media-cache.cinematerial.com/p/500x/fac5mjzg/unforgiven-movie-poster.jpg?v=1633908999`,
    description: `Unforgiven is a 1992 American Revisionist Western film starring and directed by Clint Eastwood, who produced, and written by David Webb Peoples. The film tells the story of William Munny, an aging outlaw and killer who takes on one more job, years after he had turned to farming. The film co-stars Gene Hackman, Morgan Freeman, and Richard Harris.`,
    price: 1.99,
  },
  {
    title: "Tootsie",
    director: "Sydney Pollack",
    year: 1982,
    genre: "comedy",
    img: `https://media-cache.cinematerial.com/p/500x/jzns2cwx/tootsie-movie-poster.jpg?v=1456276856`,
    description: `Tootsie is a 1982 American satirical romantic comedy film directed by Sydney Pollack and starring Dustin Hoffman. Its supporting cast includes Pollack, Jessica Lange, Teri Garr, Dabney Coleman, Bill Murray, Charles Durning, George Gaynes, Geena Davis (in her debut) and Doris Belack. The film tells the story of a talented but volatile actor whose reputation for being difficult drives him to adopt a new identity as a woman to land a job. The film was adapted by Larry Gelbart, Barry Levinson (uncredited), Elaine May (uncredited) and Murray Schisgal from a story by Gelbart and Don McGuire.`,
    price: 1.99,
  },
  {
    title: "A Clockwork Orange",
    director: "Stanley Kubrick",
    year: 1971,
    genre: "science fiction",
    img: `https://media-cache.cinematerial.com/p/500x/i2mcarzt/a-clockwork-orange-movie-poster.jpg?v=1456248310`,
    description: `A Clockwork Orange is a 1971 dystopian crime film adapted, produced, and directed by Stanley Kubrick, based on Anthony Burgess's 1962 novel of the same name. It employs disturbing, violent images to comment on psychiatry, juvenile delinquency, youth gangs, and other social, political, and economic subjects in a dystopian near-future Britain.`,
    price: 1.99,
  },
  {
    title: "Saving Private Ryan",
    director: "Steven Spielberg",
    year: 1998,
    genre: "war",
    img: `https://media-cache.cinematerial.com/p/500x/timgoz1w/saving-private-ryan-movie-poster.jpg?v=1456232067`,
    description: `Saving Private Ryan is a 1998 American epic war film directed by Steven Spielberg and written by Robert Rodat. Set during the Battle of Normandy in World War II, the film is known for its graphic portrayal of war, especially its depiction of the Omaha Beach assault during the Normandy landings. The film follows United States Army Rangers Captain John H. Miller (Tom Hanks) and his squad (Tom Sizemore, Edward Burns, Barry Pepper, Giovanni Ribisi, Vin Diesel, Adam Goldberg, and Jeremy Davies) as they search for a paratrooper, Private first class James Francis Ryan (Matt Damon), the last surviving brother of four, the three other brothers having been killed in action.`,
    price: 1.99,
  },
  {
    title: "The Shawshank Redemption",
    director: "Frank Darabont",
    year: 1994,
    genre: "drama",
    img: `https://media-cache.cinematerial.com/p/500x/b5v2e9jg/the-shawshank-redemption-movie-poster.jpg?v=1596989012`,
    description: `The Shawshank Redemption is a 1994 American drama film written and directed by Frank Darabont, based on the 1982 Stephen King novella Rita Hayworth and Shawshank Redemption. It tells the story of banker Andy Dufresne (Tim Robbins), who is sentenced to life in Shawshank State Penitentiary for the murders of his wife and her lover, despite his claims of innocence. Over the following two decades, he befriends a fellow prisoner, contraband smuggler Ellis "Red" Redding (Morgan Freeman), and becomes instrumental in a money-laundering operation led by the prison warden Samuel Norton (Bob Gunton). William Sadler, Clancy Brown, Gil Bellows, and James Whitmore appear in supporting roles.`,
    price: 1.99,
  },
  {
    title: "Butch Cassidy and the Sundance Kid",
    director: "George Roy Hill",
    year: 1969,
    genre: "western",
    img: `https://media-cache.cinematerial.com/p/500x/atlwpfdv/butch-cassidy-and-the-sundance-kid-movie-poster.jpg?v=1456220039`,
    description: `Butch Cassidy and the Sundance Kid is a 1969 American Western Buddy film directed by George Roy Hill and written by William Goldman. Based loosely on fact, the film tells the story of Wild West outlaws Robert LeRoy Parker, known as Butch Cassidy (Paul Newman), and his partner Harry Longabaugh, the "Sundance Kid" (Robert Redford), who are on the run from a crack US posse after a string of train robberies. The pair and Sundance's lover, Etta Place (Katharine Ross), flee to Bolivia to escape the posse.`,
    price: 1.49,
  },
  {
    title: "The Silence of the Lambs",
    director: "Jonathan Demme",
    year: 1991,
    genre: ["crime", "thriller"],
    img: `https://media-cache.cinematerial.com/p/500x/fjsfwbn8/the-silence-of-the-lambs-movie-poster.jpg?v=1456232081`,
    description: `The Silence of the Lambs is a 1991 American psychological horror film directed by Jonathan Demme and written by Ted Tally, adapted from Thomas Harris's 1988 novel. It stars Jodie Foster as Clarice Starling, a young FBI trainee who is hunting a serial killer, "Buffalo Bill" (Ted Levine), who skins his female victims. To catch him, she seeks the advice of the imprisoned Dr. Hannibal Lecter (Anthony Hopkins), a brilliant psychiatrist and cannibalistic serial killer. The film also features performances from Scott Glenn, Anthony Heald and Kasi Lemmons.`,
    price: 1.99,
  },
  {
    title: "In the Heat of the Night",
    director: "Norman Jewison",
    year: 1967,
    genre: "mystery",
    img: `https://media-cache.cinematerial.com/p/500x/d24qomlf/in-the-heat-of-the-night-movie-poster.jpg?v=1456274325`,
    description: `In the Heat of the Night is a 1967 American mystery drama film directed by Norman Jewison. It is based on John Ball's 1965 novel of the same name and tells the story of Virgil Tibbs, a Black police detective from Philadelphia, who becomes involved in a murder investigation in a small town in Mississippi. It stars Sidney Poitier and Rod Steiger, and was produced by Walter Mirisch. The screenplay was written by Stirling Silliphant.`,
    price: 1.99,
  },
  {
    title: "Forrest Gump",
    director: "Robert Zemeckis",
    year: 1994,
    genre: ["comedy", "drama"],
    img: `https://media-cache.cinematerial.com/p/500x/hncfztv7/forrest-gump-movie-poster.jpg?v=1602182137`,
    description: `Forrest Gump is a 1994 American comedy-drama film directed by Robert Zemeckis and written by Eric Roth. It is based on the 1986 novel of the same name by Winston Groom and stars Tom Hanks, Robin Wright, Gary Sinise, Mykelti Williamson and Sally Field. The film follows several decades in the life of a slow-witted and kindhearted Alabama man named Forrest Gump (Hanks) and his experiences in the 20th-century United States. The film differs substantially from the novel.`,
    price: 1.99,
  },
  {
    title: "All the President's Men",
    director: "Alan J. Pakula",
    year: 1976,
    genre: "drama",
    img: `https://media-cache.cinematerial.com/p/500x/xmrrnom4/all-the-presidents-men-movie-poster.jpg?v=1456240222`,
    description: `All the President's Men is a 1976 American biographical political drama-thriller film about the Watergate scandal that brought down the presidency of Richard Nixon. Directed by Alan J. Pakula with a screenplay by William Goldman, it is based on the 1974 non-fiction book of the same name by Carl Bernstein and Bob Woodward, the two journalists investigating the Watergate scandal for The Washington Post.`,
    price: 1.99,
  },
  {
    title: "Modern Times",
    director: "Charlie Chaplin",
    year: 1936,
    genre: "comedy",
    img: `https://media-cache.cinematerial.com/p/500x/fbdgydbh/modern-times-movie-poster.jpg?v=1456430251`,
    description: `Modern Times is a 1936 American silent satirical romantic black comedy film written and directed by Charlie Chaplin in which his iconic Little Tramp character struggles to survive in the modern, industrialized world. The film is a commentary on the desperate employment and financial conditions many people faced during the Great Depression — conditions created, in Chaplin's view, by the efficiencies of modern industrialization.`,
    price: 1.49,
  },
  {
    title: "The Wild Bunch",
    director: "Sam Peckinpah",
    year: 1969,
    genre: "western",
    img: `https://media-cache.cinematerial.com/p/500x/0rhil6vu/the-wild-bunch-movie-poster.jpg?v=1456192774`,
    description: `The Wild Bunch is a 1969 American epic Revisionist Western film directed by Sam Peckinpah and starring William Holden, Ernest Borgnine, Robert Ryan, Edmond O'Brien, Ben Johnson and Warren Oates. The plot concerns an aging outlaw gang on the Mexico-United States border trying to adapt to the changing modern world of 1913.`,
    price: 1.29,
  },
  {
    title: "The Apartment",
    director: "Billy Wilder",
    year: 1960,
    genre: ["comedy", "drama"],
    img: `https://media-cache.cinematerial.com/p/500x/bmkal7jy/the-apartment-movie-poster.jpg?v=1456214305`,
    description: `The Apartment is a 1960 American romantic comedy-drama film directed and produced by Billy Wilder from a screenplay he co-wrote with I. A. L. Diamond. It stars Jack Lemmon, Shirley MacLaine, Fred MacMurray, Ray Walston, Jack Kruschen, David Lewis, Willard Waterman, David White, Hope Holiday and Edie Adams.`,
    price: 1.99,
  },
  {
    title: "Spartacus",
    director: "Stanley Kubrick",
    year: 1960,
    genre: ["epic", "historical"],
    img: `https://media-cache.cinematerial.com/p/500x/brtqkzku/spartacus-movie-poster.jpg?v=1456832910`,
    description: `Spartacus was a Thracian gladiator who, along with Crixus, Gannicus, Castus, and Oenomaus, was one of the escaped slave leaders in the Third Servile War, a major slave uprising against the Roman Republic. Little is known about him beyond the events of the war, and surviving historical accounts are sometimes contradictory. All sources agree that he was a former gladiator and an accomplished military leader.`,
    price: 1.99,
  },
  {
    title: "Sunrise: A Song of Two Humans",
    director: "F. W. Murnau",
    year: 1927,
    genre: "drama",
    img: `https://media-cache.cinematerial.com/p/500x/eodauvqz/sunrise-a-song-of-two-humans-movie-poster.jpg?v=1590399977`,
    description: `Sunrise: A Song of Two Humans (also known as Sunrise) is a 1927 American silent romantic drama directed by German director F. W. Murnau (in his American film debut) and starring George O'Brien, Janet Gaynor, and Margaret Livingston. The story was adapted by Carl Mayer from the short story "The Excursion to Tilsit", from the 1917 collection with the same title by Hermann Sudermann.`,
    price: 1.99,
  },
  {
    title: "Titanic",
    director: "James Cameron",
    year: 1997,
    genre: ["epic", "romance", "drama"],
    img: `https://media-cache.cinematerial.com/p/500x/0f0v4qo6/titanic-movie-poster.jpg?v=1456630107`,
    description: `Titanic is a 1997 American epic romance and disaster film directed, written, produced, and co-edited by James Cameron. Incorporating both historical and fictionalized aspects, it is based on accounts of the sinking of the RMS Titanic, and stars Leonardo DiCaprio and Kate Winslet as members of different social classes who fall in love aboard the ship during its ill-fated maiden voyage. Also starring are Billy Zane, Kathy Bates, Frances Fisher, Gloria Stuart, Bernard Hill, Jonathan Hyde, Victor Garber, and Bill Paxton.`,
    price: 1.99,
  },
  {
    title: "Easy Rider",
    director: "Dennis Hopper",
    year: 1969,
    genre: ["drama"],
    img: `https://media-cache.cinematerial.com/p/500x/g5yyryqq/easy-rider-movie-poster.jpg?v=1456210062`,
    description: `Easy Rider is a 1969 American independent road drama film written by Peter Fonda, Dennis Hopper, and Terry Southern, produced by Fonda, and directed by Hopper. Fonda and Hopper play two bikers who travel through the American Southwest and South, carrying the proceeds from a cocaine deal. The success of Easy Rider helped spark the New Hollywood era of filmmaking during the early 1970s.`,
    price: 1.99,
  },
  {
    title: "A Night at the Opera",
    director: "Sam Wood",
    year: 1935,
    genre: "comedy",
    img: `https://media-cache.cinematerial.com/p/500x/bt0js7me/a-night-at-the-opera-movie-poster.jpg?v=1456788802`,
    description: `A Night at the Opera is a 1935 American comedy film starring the Marx Brothers (Groucho Marx, Harpo Marx and Chico Marx), and featuring Kitty Carlisle, Allan Jones, Margaret Dumont, Sig Ruman, and Walter Woolf King. It was the first of five films the Marx Brothers made under contract for Metro-Goldwyn-Mayer after their departure from Paramount Pictures, and the first after Zeppo left the act. The film was written by George S. Kaufman and Morrie Ryskind from a story by James Kevin McGuinness, with additional uncredited dialogue by Al Boasberg. The film was directed by Sam Wood.`,
    price: 1.99,
  },
  {
    title: "Platoon",
    director: "Oliver Stone",
    year: 1986,
    genre: "war",
    img: `https://media-cache.cinematerial.com/p/500x/tfpktv3j/platoon-movie-poster.jpg?v=1456279860`,
    description: `Platoon is a 1986 American war film written and directed by Oliver Stone, starring Tom Berenger, Willem Dafoe, Charlie Sheen, Keith David, Kevin Dillon, John C. McGinley, Forest Whitaker, and Johnny Depp. It is the first film of a trilogy of Vietnam War films directed by Stone, followed by Born on the Fourth of July (1989) and Heaven & Earth (1993). The film, based on Stone's experience from the war, follows a U.S. Army volunteer (Sheen) serving in Vietnam while his Platoon Sergeant and his Squad Leader (Berenger and Dafoe) argue over the morality in the platoon and of the war itself.`,
    price: 1.99,
  },
  {
    title: "12 Angry Men",
    director: "Sidney Lumet",
    year: 1957,
    genre: "drama",
    img: `https://media-cache.cinematerial.com/p/500x/c5whwpvz/12-angry-men-theatrical-movie-poster.jpg?v=1456708298`,
    description: `12 Angry Men is a 1957 American courtroom drama film directed by Sidney Lumet, adapted from a 1954 teleplay of the same name by Reginald Rose. The film tells the story of a jury of 12 men as they deliberate the conviction or acquittal of a teenager charged with murder on the basis of reasonable doubt; disagreement and conflict among them force the jurors to question their morals and values. It stars Henry Fonda (who also produced the film with Reginald Rose), Lee J. Cobb, Ed Begley, E. G. Marshall, and Jack Warden.`,
    price: 1.99,
  },
  {
    title: "Bringing Up Baby",
    director: "Howard Hawks",
    year: 1938,
    genre: "comedy",
    img: `https://media-cache.cinematerial.com/p/500x/ahxmjmpq/bringing-up-baby-theatrical-movie-poster.jpg?v=1456214013`,
    description: `Bringing Up Baby is a 1938 American screwball comedy film directed by Howard Hawks, and starring Katharine Hepburn and Cary Grant. It was released by RKO Radio Pictures. The film tells the story of a paleontologist in a number of predicaments involving a scatterbrained heiress and a leopard named Baby. The screenplay was adapted by Dudley Nichols and Hagar Wilde from a short story by Wilde which originally appeared in Collier's Weekly magazine on April 10, 1937.`,
    price: 1.99,
  },
  {
    title: "The Sixth Sense",
    director: "M. Night Shyamalan",
    year: 1999,
    genre: "thriller",
    img: `https://media-cache.cinematerial.com/p/500x/v6a9hdoz/the-sixth-sense-movie-poster.jpg?v=1456245070`,
    description: `The Sixth Sense is a 1999 American psychological thriller film written and directed by M. Night Shyamalan. It stars Bruce Willis as a child psychologist whose patient (Haley Joel Osment) claims he can see and talk to the dead.`,
    price: 1.99,
  },
  {
    title: "Swing Time",
    director: "George Stevens",
    year: 1936,
    genre: ["musical", "romance"],
    img: `https://media-cache.cinematerial.com/p/500x/l2wvoerw/swing-time-movie-poster.jpg?v=1456288803`,
    description: `Swing Time is a 1936 American musical comedy film, the sixth of ten starring Fred Astaire and Ginger Rogers. Directed by George Stevens for RKO, it features Helen Broderick, Victor Moore, Betty Furness, Eric Blore and Georges Metaxa, with music by Jerome Kern and lyrics by Dorothy Fields. Set mainly in New York City, the film follows a gambler and dancer, "Lucky" (Astaire), who is trying to raise money to secure his marriage when he meets dance instructor Penny (Rogers) and begins dancing with her; the two soon fall in love and are forced to reconcile their feelings.`,
    price: 1.69,
  },
  {
    title: "Sophie's Choice",
    director: "Alan J. Pakula",
    year: 1982,
    genre: "drama",
    img: `https://media-cache.cinematerial.com/p/500x/aefb6mh1/sophies-choice-movie-poster.jpg?v=1456216673`,
    description: `Sophie's Choice is a 1982 American drama film directed and written by Alan J. Pakula, adapted from William Styron's 1979 novel Sophie's Choice. The film stars Meryl Streep as Zofia "Sophie" Zawistowski, a Polish immigrant to America with a dark secret from her past who shares a boarding house in Brooklyn with her tempestuous lover Nathan (Kevin Kline in his first feature film), and young writer Stingo (Peter MacNicol). It also features Rita Karin, Stephen D. Newman and Josh Mostel.`,
    price: 1.99,
  },
  {
    title: "Goodfellas",
    director: "Martin Scorsese",
    year: 1990,
    genre: "crime",
    img: `https://media-cache.cinematerial.com/p/500x/1njawphu/goodfellas-french-movie-poster.jpg?v=1456770873`,
    description: `Goodfellas (stylized GoodFellas) is a 1990 American biographical crime film directed by Martin Scorsese, written by Nicholas Pileggi and Scorsese, and produced by Irwin Winkler. It is a film adaptation of the 1985 nonfiction book Wiseguy by Pileggi. Starring Robert De Niro, Ray Liotta, Joe Pesci, Lorraine Bracco and Paul Sorvino, the film narrates the rise and fall of mob associate Henry Hill and his friends and family from 1955 to 1980.`,
    price: 1.99,
  },
  {
    title: "The French Connection",
    director: "William Friedkin",
    year: 1971,
    genre: ["crime", "action"],
    img: `https://media-cache.cinematerial.com/p/500x/jqi7tya4/the-french-connection-movie-poster.jpg?v=1456851589`,
    description: `The French Connection is a 1971 American crime action thriller film directed by William Friedkin. The screenplay, written by Ernest Tidyman, is based on Robin Moore's 1969 book of the same name. It tells the story of NYPD detectives Jimmy "Popeye" Doyle and Buddy "Cloudy" Russo, whose real-life counterparts were Narcotics Detectives Eddie Egan and Sonny Grosso, in pursuit of wealthy French heroin smuggler Alain Charnier. The film stars Gene Hackman as Popeye, Roy Scheider as Cloudy, and Fernando Rey as Charnier. Tony Lo Bianco and Marcel Bozzuffi also star.`,
    price: 1.99,
  },
  {
    title: "Pulp Fiction",
    director: "Quentin Tarantino",
    year: 1994,
    genre: "crime",
    img: `https://media-cache.cinematerial.com/p/500x/hmc4otl5/pulp-fiction-theatrical-movie-poster.jpg?v=1479233327`,
    description: `Pulp Fiction is a 1994 American crime film written and directed by Quentin Tarantino, who conceived it with Roger Avary. Starring John Travolta, Samuel L. Jackson, Bruce Willis, Tim Roth, Ving Rhames, and Uma Thurman, it tells several stories of crime in Los Angeles. The title refers to the pulp magazines and hardboiled crime novels popular during the mid-20th century, known for their graphic violence and punchy dialogue.`,
    price: 1.99,
  },
  {
    title: "The Last Picture Show",
    director: "Peter Bogdanovich",
    year: 1971,
    genre: "drama",
    img: `https://media-cache.cinematerial.com/p/500x/f4bvd1aw/the-last-picture-show-movie-poster.jpg?v=1456243337`,
    description: `The Last Picture Show is a 1971 American coming-of-age drama film directed and co-written by Peter Bogdanovich, adapted from the semi-autobiographical 1966 novel The Last Picture Show by Larry McMurtry. The film's ensemble cast includes Timothy Bottoms, Jeff Bridges, Ellen Burstyn, Ben Johnson, Cloris Leachman, and Cybill Shepherd. Set in a small town in northern Texas from November 1951 to October 1952, it is a story of two high-school seniors and long-time friends, Sonny Crawford (Bottoms) and Duane Jackson (Bridges).`,
    price: 1.69,
  },
  {
    title: "Do the Right Thing",
    director: "Spike Lee",
    year: 1989,
    genre: "drama",
    img: `https://media-cache.cinematerial.com/p/500x/z2xghe0f/do-the-right-thing-movie-poster.jpg?v=1456016050`,
    description: `Do the Right Thing is a 1989 American comedy-drama film produced, written, and directed by Spike Lee. It stars Lee, Danny Aiello, Ossie Davis, Ruby Dee, Richard Edson, Giancarlo Esposito, Bill Nunn, John Turturro, and Samuel L. Jackson, and is the feature film debut of Martin Lawrence and Rosie Perez. The story explores a Brooklyn neighborhood's simmering racial tension between its African-American residents and the Italian-American owners of a local pizzeria, culminating in tragedy and violence on a hot summer day.`,
    price: 1.99,
  },
  {
    title: "Blade Runner",
    director: "Ridley Scott",
    year: 1982,
    genre: "science fiction",
    img: `https://media-cache.cinematerial.com/p/500x/dnj4dmrq/blade-runner-movie-poster.jpg?v=1515091291`,
    description: `Blade Runner is a 1982 science fiction film directed by Ridley Scott, and written by Hampton Fancher and David Peoples. Starring Harrison Ford, Rutger Hauer, Sean Young, and Edward James Olmos, it is an adaptation of Philip K. Dick's 1968 novel Do Androids Dream of Electric Sheep? The film is set in a dystopian future Los Angeles of 2019, in which synthetic humans known as replicants are bio-engineered by the powerful Tyrell Corporation to work on space colonies. When a fugitive group of advanced replicants led by Roy Batty (Hauer) escapes back to Earth, burnt-out cop Rick Deckard (Ford) reluctantly agrees to hunt them down.`,
    price: 1.99,
  },
  {
    title: "Yankee Doodle Dandy",
    director: "Michael Curtiz",
    year: 1942,
    genre: "musical",
    img: `https://media-cache.cinematerial.com/p/500x/goxa0sxx/yankee-doodle-dandy-theatrical-movie-poster.jpg?v=1456321045`,
    description: `Yankee Doodle Dandy is a 1942 American biographical musical film about George M. Cohan, known as "The Man Who Owned Broadway". It stars James Cagney, Joan Leslie, Walter Huston, and Richard Whorf, and features Irene Manning, George Tobias, Rosemary DeCamp, Jeanne Cagney, and Vera Lewis. Joan Leslie's singing voice was partially dubbed by Sally Sweetland.`,
    price: 1.99,
  },
  {
    title: "Toy Story",
    director: "John Lasseter",
    year: 1995,
    genre: ["children's", "fantasy"],
    img: `https://upload.wikimedia.org/wikipedia/en/1/13/Toy_Story.jpg`,
    description: `Toy Story is a 1995 American computer-animated comedy film directed by John Lasseter (in his feature directorial debut), produced by Pixar Animation Studios and released by Walt Disney Pictures. The first installment in the Toy Story franchise, it was the first entirely computer-animated feature film, as well as the first feature film from Pixar.`,
    price: 1.99,
  },
  {
    title: "Ben-Hur",
    director: "William Wyler",
    year: 1959,
    genre: "epic",
    img: `https://media-cache.cinematerial.com/p/500x/fjgqxvzc/ben-hur-movie-poster.jpg?v=1456202736`,
    description: `Ben-Hur is a 1959 American religious epic film directed by William Wyler, produced by Sam Zimbalist, and starring Charlton Heston as the title character. A remake of the 1925 silent film with a similar title, it was adapted from Lew Wallace's 1880 novel Ben-Hur: A Tale of the Christ. The screenplay is credited to Karl Tunberg, but includes contributions from Maxwell Anderson, S. N. Behrman, Gore Vidal, and Christopher Fry.`,
    price: 1.99,
  },
];

module.exports = films;
